apiVersion: v1
kind: Secret
metadata:
  name: practice-dashboard-gateway-secret
  namespace: practice-dashboard-gateway
type: Opaque
stringData:
  AZURE_TENANT_ID: "5e45e2ef-d6aa-4ad1-aaca-a7187394a753"
  AZURE_CLIENT_ID: "ce00c467-f4c4-469f-a695-620d11073fde"